### ISSUE TITLE
Get washing machine

### ISSUE THREAD

**Issue by ghost** [joemilbourn/house#10]
AEG L87695WD: http://www.johnlewis.com/store/aeg-l87695wd-washer-dryer-9kg-wash-7kg-dry-load-a-energy-rating-1600rpm-spin-white/p231616430?navAction=jump&_requestid=10014799

**Comment by ghost** [comment]
41482664 14 December 2013 12:48
￼Order receipt UK Delivery
Order Summary
Dr Maria Keays 6, Brookside Orwell
Royston Hertfordshire SG8 5TQ United Kingdom 07730682379 07732330846
￼
Standard Delivery ­ Friday 20 December 2013 2 PM to 9 PM Free
￼1 x AEG L87695WD Washer Dryer, 9kg Wash/7kg Dry Load, A Energy Rating, 1600rpm Spin, White ProductCode : 88920603
£819.00
£819.00 Free
£819.00
￼￼Order total
Payment details
Payment type Card number Cardholder Email address
Payment amount Any questions?
Total Delivery charge
Total payable
￼Visa Debit
***\* ***\* ***\* 5210
MISS MC KEAYS maria.keays@gmail.com
£819.00
(partial number shown for security)
￼￼Call johnlewis.com customer services on 08456 049 049, from 7am to midnight, 7 days a week Track your order
Access your account to view the status of your order, view your order details, or print out a VAT receipt (after payment has been processed)
￼Please Note: This acknowledges that your order has been received but does not confirm acceptance of the order by johnlewis.com. Acceptance will take place upon order despatch subject to confirmation of stock availablity, verification of payment details and validation of all product description and product price. Please note, your payment will not be processed until your order is ready to be dispatched. If there are any problems with your order you will be contacted by our customer service team.
johnlewis.com is secure
and your details are protected
Copyright © john Lewis Partnership 2001­2013
john Lewis plc Registered office: 171 Victoria Street, London SW1E 5NN. Registered in England.
Company registration number: 233462. VAT no: GB232457280
Send us your feedback
￼￼￼￼

**Comment by ghost** [comment]
Thank you for your order
Dear Keays

Our guarantee for your new product 

Thank you for purchasing the following from John Lewis : 
AEG L87695WD Washer Dryer, 9kg Wash/7kg Dry Load, A Energy Rating, 1600rpm Spin, White

In addition to the first year manufacturer's guarantee, John Lewis plc provides a second year guarantee, subject to the terms and conditions below.

If you purchased a John Lewis own brand appliance, your guarantee is automatically three years, and five years in the case of any brand of television.

(If you purchased a John Lewis Plan with your appliance, your fulfilment letter will be posted to you within 28 days from the John Lewis Plan Administrators.)

What does the guarantee cover?
Our guarantee provides full cover against mechanical breakdown through normal use. This means that if your item develops a fault during the guarantee period, we'll arrange for it to be repaired free of charge, including all parts and labour. And your guarantee is transferrable with ownership, so if you give or sell the item to someone during the guarantee period, it's still covered.                      

How does it work?
     If during the guarantee period your purchase develops a fault that needs to be repaired, please contact your local John Lewis shop and talk to one of our Partners. If you are some distance from a store, please call our Technical Support team on 0844 6931799 to report the breakdown.

You'll need to provide us with details of your item, including the model number and date of purchase.

If we can't repair your item, we'll replace it with an item of equivalent specification. If no equivalent product is available, we'll discuss an alternative settlement with you, and we'll always do our best to make sure that you're satisfied with the outcome.

What's not included?
There are some specific exclusions from our guarantees, as follows:

Repair costs caused by external factors such as computer viruses, faulty software, fire, theft and weather (including lightning damage)

Accidental damage, for example if your item has been dropped. You may find that this type of damage is covered by your household contents insurance policy.

Imagine ghosting or screen burn. These can appear on a screen that's left operating for a prolonged period with either a still image or channel constantly displaying a logo.

Pixel spots. These are tiny dark or bright spots that may become visible on a screen.

Digital television picture affected by any of the following; a misaligned or unsuitable material, climatic conditions, geographic location, poor quality or low strength broadcast signal.

If the product has been used commercially or for business purposes.

Deliberate damage to or neglect of the product.

Consumables such as batteries, ink cartridges, storage media, rear projection television bulbs, fuses and light bulbs.

Cosmetic items such as cabinet trim, scratches, dents, corrosion or colour where the function of the product is unaffected.

The unblocking of drainage channels in refrigeration equipment.

Any loss suffered as a result of not being able to use the product, or any loss over and above the purchase price of the item.

Frozen food loss as a result of the product breaking down.

Servicing, inspecting or cleaning of the insured product; and failure to follow the manufacturer's instructions and/or installation guidelines.

If you did not buy a John Lewis Plan at the time of purchasing the appliance, but would like to do so now, please check online at www.johnlewis.com/serviceplan or telephone the John Lewis Plan Administrators on 0844 871 7771. If you decide to apply, please do so within 30 days of your appliance being delivered.
I hope you enjoy using your new appliance. Thank you for shopping with Johnlewis.  
Thank you for shopping with John Lewis.

Yours sincerely, 

Customer Services
John Lewis

**Comment by ghost** [comment]
coming between 14:00 and 21:00 on 2013-12-20

**Comment by joemilbourn** [comment]
Delivered, and installed.
