### ISSUE TITLE
Book van for 21st-22nd

### ISSUE THREAD

**Issue by joemilbourn** [joemilbourn/house#14]

**Comment by ghost** [comment]
On www.enterprise.co.uk : 

Renault Master, Long Wheelbase Ford Transit or similar
Hi-Roof
4 doors
3 seater
AM/FM stereo
Power steering

Start:  21 Dec 2013,09:00
End:  23 Dec 2013,09:00

estimated at £ 300.32 GBP

what do you think?

**Comment by ghost** [comment]
![enterprise](https://f.cloud.github.com/assets/6168970/1743498/cf81f26a-640d-11e3-9743-91d5bfddbfc3.png)
 booked :)
