### ISSUE TITLE
Cancel BT

### ISSUE THREAD

**Issue by ghost** [joemilbourn/house#21]

**Comment by joemilbourn** [comment]
How to contact us
If you want to cancel your phone service please call us on the numbers below between 8am-8pm, Monday to Friday or 9am-6pm at weekends. This dedicated team will be able to deal with your request.
Please have your account number ready (it’s on your bill).
From a landline: 0800 345 7310
From a mobile: 0330 123 4150*
From abroad: +44 179 359 6931**

**Comment by joemilbourn** [comment]
Done
