### ISSUE TITLE
BQ list

### ISSUE THREAD

**Issue by joemilbourn** [joemilbourn/house#41]
White paint - bathroom?
Ladder, should work on stairs and loft
Pack of three shall dust sheets
Masking take

**Comment by joemilbourn** [comment]
Solar powered flood light

**Comment by ghost** [comment]
a light bulb for attic bathroom

**Comment by ghost** [comment]
This seems like a nice ladder? http://www.diy.com/nav/build/ladders/combination-ladders/Abru-Aluminium-3-Way-Telescopic-Combination-Ladder-H-4-09m-12167529

**Comment by ghost** [comment]
This one is cheaper: http://www.diy.com/nav/build/ladders/combination-ladders/Abru-3-Way-9-Tread-Combination-Ladder-H-2-74m-9273855

**Comment by joemilbourn** [comment]
This is the one I'd looked at, 127 squid.

**Comment by ghost** [comment]
http://www.diy.com/nav/build/ladders/combination-ladders/Abru-5-Way-Combination-Ladder-and-Platform-H-1-87m-10597528
