### ISSUE TITLE
connect electric

### ISSUE THREAD

**Issue by joemilbourn** [joemilbourn/house#6]

**Comment by ghost** [comment]
Go with NPower. Set up when joint account address moved.

**Comment by ghost** [comment]
Meter reading from 2013-12-11: 65877

**Comment by ghost** [comment]
Going with Ovo as they've got our details and are cheaper than Npower. My Ovo ID is 100287522. Have tried to log in by no email on account so have emailed for a password

**Comment by ghost** [comment]
Have to set up email on phone.

**Comment by ghost** [comment]
Set up, they will email Joe. Paying by direct debit from joint account. Hopefully can add Maria's email to account as well, all online, no paper bills, submit meter readings online.

Account details:
- Account number: 2348192
- My Ovo ID: 100287522
